fn main() {
    // Embed the app icon into the Windows .exe so it appears in Explorer
    // and in the taskbar.  The .ico is generated by CI from Logo/CDG Logo.png
    // before `cargo build` runs; skip silently if it doesn't exist (local builds).
    #[cfg(windows)]
    {
        let ico = std::path::Path::new("Logo/CDG Logo.ico");
        if ico.exists() {
            println!("cargo:rerun-if-changed=Logo/CDG Logo.ico");
            let mut res = winres::WindowsResource::new();
            res.set_icon("Logo/CDG Logo.ico");
            res.compile().expect("Failed to embed Windows icon");
        }
    }
}
